### ISSUE TITLE
Please add a setup.py to simplify installation

### ISSUE THREAD

**Issue by liorgolgher** [Damseh/VascularGraph#1]
Greetings,

Thank you very much for sharing this package!

I'd like to flex its muscles on my 3D and 4D vascular datasets. Can you please add a setup.py to simplify its installation into a dedicated conda environment?

Many thanks,
Lior
Pablo Blinder Lab

**Comment by Damseh** [comment]
Hi Lior, 
It is updated now! 
Best,
Rafat

**Comment by liorgolgher** [comment]
Thanks a lot Rafat!

Until the package becomes conda/pip installable, you might want to add the clone git step to your [installation instructions](https://github.com/Damseh/VascularGraph/blob/master/README.rst#to-install).

Currently I'm facing some /Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx error raised through the VNC connection to our server. I sure look forward to resolving it and using your much-needed cool package.


Best,
Lior
